### ISSUE TITLE
Metadata for newer books

### ISSUE THREAD

**Issue by jaytula** [hugovk/gutenberg-metadata#14]
I noticed that very new books since the last run aren't in the `gutenbook-metadata.json`. I guess that is expected. Will this be updated periodically?

**Comment by hugovk** [comment]
I aim to update it at least annually in late October, in time for [NaNoGenMo](https://nanogenmo.github.io/).

Partly it's so seldom because it's a bit tricky to get the tooling installed, so I've been digging out an old machine each year. But I've just got it working on this machine so have pushed an update!

**Comment by jaytula** [comment]
Awesome!
